### ISSUE TITLE
Add config flags for non-interactive input

### ISSUE THREAD

**Issue by cthos** [chrisweight/cjw-cli#1]
As a developer
When I create a project with cw
I'd like to pass my configuration options such as "--project-name" to cw in a single command invocation
So that I can alias it and reference it more easily in scripts.

> tl;dr - I need to be able to pass in anything you ask interactively on the command line.

**Comment by chrisweight** [comment]
Taken care of with merge of https://github.com/chrisweight/cjw-cli/tree/improvement-optional-cmd-args to master
